version: '3.8'
services:
  newsgpt-ui-api-python:
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - .env
    ports: 
      - 8080:8080
      - 8501:8501
    stdin_open: true
    tty: true
